services:
  main_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: main_service
    image: main_service:latest
    container_name: main_service
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_USERNAME: default
      SPRING_DATA_REDIS_PASSWORD: redis
      PAYMENT_SERVICE_URL: http://payment:8081
      # Настройки OAuth2 клиента
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SHOP-CLIENT_CLIENT-ID: shop-client
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SHOP-CLIENT_CLIENT-SECRET: shop-secret
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SHOP-CLIENT_SCOPE: payment.read,payment.write
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SHOP-CLIENT_AUTHORIZATION-GRANT-TYPE: client_credentials
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SHOP-CLIENT_PROVIDER: auth-server
      # Настройки провайдера OAuth2
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTH-SERVER_TOKEN-URI: http://auth_server:9000/oauth2/token
    ports:
      - "8080:8080"
    networks:
      - shop_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth_server:
        condition: service_healthy

  payment:
    build:
      context: .
      dockerfile: Dockerfile
      target: payment
    image: payment:latest
    container_name: payment
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWK_SET_URI: http://auth_server:9000/oauth2/jwks
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth_server:9000
    ports:
      - "8081:8081"
    networks:
      - shop_network
    depends_on:
      db:
        condition: service_healthy
      auth_server:
        condition: service_healthy

  auth_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth_server
    image: auth_server:latest
    container_name: auth_server
    ports:
      - "9000:9000"
    networks:
      - shop_network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  db:
    image: postgres:17
    container_name: shop_db
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shop_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: shop_redis
    ports:
      - "6379:6379"
    networks:
      - shop_network
    volumes:
      - redis_data:/data
    command: redis-server --protected-mode no
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  shop_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local