services:
  shop:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop:latest
    container_name: shop_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shop_db:5432/shop_db
    command: java -jar target/shop-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    networks:
      - shop_network
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: shop_db
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shop_network

networks:
  shop_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local