services:
  shop:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop:latest
    container_name: shop_app
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
    command: java -jar target/shop-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    networks:
      - shop_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: shop_db
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shop_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  shop_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local